spring:
  cool-sms:
    api-key:
    api-secret:
    caller-number:
  imp:
    code:
    api:
      key:
      secretkey:
  cors:
    allowed_origins: ${ALLOWED_ORIGINS}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
  openai:
    secret-key: ${OPENAI_API_SECRET_KEY}

