spring:
  cool-sms:
    api-key: ${COOL_SMS_API_KEY}
    api-secret: ${COOL_SMS_API_SECRET}
    caller-number: ${COOL_SMS_CALLER_NUMBER}

  cors:
    allowed_origins: ${ALLOWED_ORIGINS}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET}

  openai:
    secret-key: ${OPENAI_SECRET}
  cloud:
    aws:
      credentials:
        access-Key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2

aws:
  s3:
    bucket: jamjam2025
server:
  forward-headers-strategy: native